# Generated by Django 4.1.7 on 2023-03-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimages',
            old_name='imgae',
            new_name='image',
        ),
    ]
