# Generated by Django 4.1.7 on 2023-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
