# Generated by Django 4.1.7 on 2023-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_members_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='photo',
            field=models.ImageField(default=1, upload_to='static/uploads/'),
            preserve_default=False,
        ),
    ]
