# Generated by Django 4.1.7 on 2023-03-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_rename_members_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='static/uploads/'),
            preserve_default=False,
        ),
    ]
