# Generated by Django 4.1.7 on 2023-03-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_event_url_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
