# Generated by Django 4.1.7 on 2023-04-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_meta_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('terms', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
