# Generated by Django 4.1.7 on 2023-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sitedata_delete_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='discord_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedata',
            name='github_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedata',
            name='instagram_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedata',
            name='linkedin_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedata',
            name='twitter_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
