# Generated by Django 4.1.7 on 2023-04-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sitedata_discord_url_sitedata_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
