# Generated by Django 4.2 on 2023-04-07 11:43

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_sliderimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '900x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='static/uploads/'),
        ),
    ]
