# Generated by Django 4.2 on 2023-04-07 12:11

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sliderimage_cropping_alter_sliderimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '200x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='member',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
