# Generated by Django 4.2 on 2023-04-07 12:24

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_member_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cropping',
        ),
        migrations.AddField(
            model_name='member',
            name='aspect_ratio_height',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='aspect_ratio_width',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=image_cropping.fields.ImageCropField(upload_to='static/uploads/'),
        ),
    ]
