# Generated by Django 4.2 on 2023-04-07 12:27

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_member_cropping_member_aspect_ratio_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='aspect_ratio_height',
        ),
        migrations.RemoveField(
            model_name='member',
            name='aspect_ratio_width',
        ),
        migrations.AddField(
            model_name='member',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
