# Generated by Django 4.2 on 2023-04-07 12:29

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_member_aspect_ratio_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '250x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
