# Generated by Django 4.2 on 2023-04-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_event_cropping_alter_member_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('yonetimKurulu', 'yonetimKurulu'), ('denetlemeKurulu', 'denetlemeKurulu'), ('toplulukBaskani', 'toplulukBaskani')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
