# Generated by Django 4.2 on 2023-04-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_event_image_alter_member_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='photo',
            new_name='image',
        ),
    ]
