# Generated by Django 4.2 on 2023-04-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_positioncategories_alter_member_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionCategories',
            new_name='PositionCategory',
        ),
        migrations.RenameField(
            model_name='sitedata',
            old_name='terms',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='sitedata',
            old_name='url',
            new_name='document_url',
        ),
    ]
