# Generated by Django 4.2 on 2023-04-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_positioncategories_positioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cropped_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='cropped_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='cropped_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
