# Generated by Django 4.2 on 2023-04-17 08:39

from django.db import migrations, models
import image_cropping.admin
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_event_cropped_image_member_cropped_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '250x250', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('cropped_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=(image_cropping.admin.ImageCroppingMixin, models.Model),
        ),
    ]
