# Generated by Django 4.2 on 2023-04-18 22:26

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_name_gallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='cropping',
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover',
            field=models.ImageField(default=1, upload_to='gallery/cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1000x1000', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cover cropping'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='cropped_cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1000x1000', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
    ]
