# Generated by Django 4.2 on 2023-04-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_gallery_cover_cropping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='cover',
        ),
    ]
