# Generated by Django 4.2 on 2023-04-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_gallery_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='gallery_header',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
