# Generated by Django 4.2 on 2023-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_event_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='identifier',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
