# Generated by Django 4.2 on 2023-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_event_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='positioncategory',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='event',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='positioncategory',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
