# Generated by Django 4.2 on 2023-04-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_event_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='twitter_url',
        ),
    ]
